backend:
  name: github
  repo: literaryno4/literaryno4.github.io
  branch: master

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "posts"
    label: "博客文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "分类", name: "categories", widget: "string", default: "jekyll update" }
      - label: "标签"
        name: "tags"
        widget: "list"
        required: false
      - { label: "MathJax", name: "mathjax", widget: "boolean", default: false, required: false }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "pages"
    label: "页面"
    editor:
      preview: false
    files:
      - label: "关于页面"
        name: "about"
        file: "about.markdown"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "标题", name: "title", widget: "hidden", default: "About" }
          - { label: "链接", name: "permalink", widget: "hidden", default: "/about/" }
          - { label: "正文", name: "body", widget: "markdown" }
